Repository glue-viz/glue-astronomy, pull requests merged in 2023-01, with the labels that each got.

#79 Structure CI Workflows
  .github/workflows/main.yml
  tox.ini
Labels: testing, no-changelog-entry-needed

#80 Setup automated changelog generation for release process
  .github/release.yml
  .github/workflows/update-changelog.yaml
  CHANGES.md
  CHANGES.rst
  MANIFEST.in
  RELEASE.rst
Labels: documentation, no-changelog-entry-needed

#82 Fixed return type and shape for pixel <-> world conversions in SpectralCoordinates
  glue_astronomy/spectral_coordinates.py
  glue_astronomy/tests/__init__.py
  glue_astronomy/tests/test_spectral_coordinates.py
  glue_astronomy/translators/tests/test_spectrum1d.py
Labels: bug

#84 Accept `component.units=None` in translators input
  glue_astronomy/translators/nddata.py
  glue_astronomy/translators/spectral_cube.py
  glue_astronomy/translators/spectrum1d.py
Labels: bug

#85 Add glue-core to devdeps
  tox.ini
Labels: testing, no-changelog-entry-needed
